const LOAD_TASKLIST = "LOAD_TASKLIST";
const LOAD_TASK = "LOAD_TASK";
const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const LOAD_TASKLIST_SUCCESS = "LOAD_TASKLIST_SUCCESS";
const LOAD_TASKLIST_FAILED = "LOAD_TASKLIST_FAILED";
export {LOAD_TASKLIST, LOAD_TASK, ADD_TASK, REMOVE_TASK, LOAD_TASKLIST_SUCCESS, LOAD_TASKLIST_FAILED};